[pytest]
# 命令行参数：显示详细日志，输出到终端，指定报告路径
addopts = -vs --html=reports/report.html --self-contained-html
# 测试搜索路径
testpaths = ./tests
# 测试文件命名规则
python_files = test_*.py
# 测试类/函数命名规则
python_classes = Test*
python_functions = test_*